export const categories = [
  { "regional": "Regional" },
  { "technology": "Tecnología" },
  { "lifestyle": "Estilo de vida" },
  { "business": "Negocios" },
  { "general": "General" },
  { "programming": "Programación" },
  { "science": "Ciencia" },
  { "world": "Mundo" },
  { "sports": "Deportes" },
  { "finance": "Finanzas" },
  { "academia": "Academia" },
  { "politics": "Política" },
  { "health": "Salud" },
  { "entertainment": "Entretenimiento" },
  { "game": "Juego" },
  { "opinion": "Opinión" },
  { "food": "Comida" },
  { "national": "Nacional" },
  { "fashion": "Moda" },
  { "society": "Sociedad" },
  { "movie": "Peliculas" }
];


export const languages = {
  Arabic: "ar",
  Chinese: "zh",
  Dutch: "nl",
  English: "en",
  Finnish: "fi",
  French: "fr",
  German: "de",
  Hindi: "hi",
  Italian: "it",
  Japanese: "ja",
  Korean: "ko",
  Malay: "msa",
  Portuguese: "pt",
  Russian: "ru",
  Spanish: "es",
};
