export  const categories = [
    "regional",
    "technology",
    "lifestyle",
    "business",
    "general",
    "programming",
    "science",
    "entertainment",
    "world",
    "sports",
    "finance",
    "academia",
    "politics",
    "health",
    "opinion",
    "food",
    "game",
  ];
  
  export  const languages = {
    Arabic: "ar",
    Chinese: "zh",
    Dutch: "nl",
    English: "en",
    Finnish: "fi",
    French: "fr",
    German: "de",
    Hindi: "hi",
    Italian: "it",
    Japanese: "ja",
    Korean: "ko",
    Malay: "msa",
    Portuguese: "pt",
    Russian: "ru",
    Spanish: "es",
  };
