export const provincias = [
  { provincia: "Buenos Aires", codigoDeEstado: "B" },
  { provincia: "Catamarca", codigoDeEstado: "K" },
  { provincia: "Chaco", codigoDeEstado: "H" },
  { provincia: "Chubut", codigoDeEstado: "U" },
  { provincia: "Córdoba", codigoDeEstado: "X" },
  { provincia: "Corrientes", codigoDeEstado: "W" },
  { provincia: "Entre Ríos", codigoDeEstado: "E" },
  { provincia: "Formosa", codigoDeEstado: "P" },
  { provincia: "Jujuy", codigoDeEstado: "Y" },
  { provincia: "La Pampa", codigoDeEstado: "L" },
  { provincia: "La Rioja", codigoDeEstado: "F" },
  { provincia: "Mendoza", codigoDeEstado: "M" },
  { provincia: "Misiones", codigoDeEstado: "N" },
  { provincia: "Neuquén", codigoDeEstado: "Q" },
  { provincia: "Río Negro", codigoDeEstado: "R" },
  { provincia: "Salta", codigoDeEstado: "A" },
  { provincia: "San Juan", codigoDeEstado: "J" },
  { provincia: "San Luis", codigoDeEstado: "D" },
  { provincia: "Santa Cruz", codigoDeEstado: "Z" },
  { provincia: "Santa Fe", codigoDeEstado: "S" },
  { provincia: "Santiago del Estero", codigoDeEstado: "G" },
  {
    provincia: "Tierra del Fuego",
    codigoDeEstado: "V",
  },
  { provincia: "Tucumán", codigoDeEstado: "T" },
];
